// heliportTemplate.ts — the POI's optional `heliport.tsc.txt` / `heliport.wad.txt` pair: two TEMPLATES a
// user can turn into a real AFS4 heliport by hand (forum #160, ApfelFlieger).
//
// WHY TEMPLATES AND NOT AN AIRPORT. A user `.tsc` whose `icao` collides with a base airport SILENTLY
// REPLACES it — the only trace is one line in tm.log — and POIs get shared, so PCT cannot validate an
// ICAO on a machine it has never seen. That is the whole reason PCT does not write airports. These files
// dodge it by construction:
//
//   • PCT never picks an identity. `icao` / `name` / `country` ship as `__PLACEHOLDER__` text; the person
//     who fills them in is the same person who moves the folder into scenery/airports.
//   • The `.txt` suffix makes them INERT wherever they sit. (Measured 2026-07-31: a `.tsc`+`.wad` dropped
//     into scenery/poi/ is not read AT ALL — the sim's `airports=` count did not move and the 36-char
//     `sname` that makes it log `airport name … too long` for files under scenery/airports/ stayed silent.
//     So even the bare names were safe; `.txt` costs the user nothing — Michael's own recipe already ends
//     in "rename the files to the airport code" — and it survives a sim update changing that.)
//
// PROVENANCE. Every tag, and the order, is copied from a heliport that WORKS: ApfelFlieger's `de0869`
// (forum #113 / thread 28713 #78), then flown end-to-end at KDAG on 2026-07-31 with these exact contents
// generated by hand. That gate settled the open questions this file used to have to guess:
//
//   `coordinate_system` = `flat` loads · `uid` 0 is fine · `airports/<continent>/<country>/<name>/` works ·
//   `radius` is METRES (the sim's own panel showed "Size 66 ft / 20 m" for radius 10) · `heading` is TRUE
//   degrees (we wrote 40, the sim showed 028 = 40 − the local magnetic variation) — so PCT's stored true
//   heading goes in verbatim, no conversion · the `objects` block below, in the `tmsimulator_scenery_objecttmslist`
//   spelling taken from the Hong Kong community pack, DOES reach the cultivation (the POI's palms did not blink).

import type { LonLat } from "../project/types";
import { tag, block, fmtLonLat, fmtNum, sanitizeValue } from "../tm/tmEmit";
import { lonToWad, latToWad, directionToWad, formatWad } from "../geo/wad";
import { headingToDirection } from "../geo/orientation";
import { ANCHOR_GEOMETRY, type Anchor } from "./plantAnchor";

/** The two template filenames. `.txt` on purpose (see the header); the user renames them to `<icao>.tsc`
 *  and `<icao>.wad`, which their recipe has them doing anyway. */
export const HELIPORT_TSC_FILE = "heliport.tsc.txt";
export const HELIPORT_WAD_FILE = "heliport.wad.txt";

/** Longest `sname` the sim accepts. It REJECTS THE WHOLE AIRPORT above the limit, with
 *  `ERROR: (airport name '…' too long. tsc='…')` — three of IPACS's own files trip it. The exact cut is
 *  somewhere in [30, 34] (30 loads, 35 fails), so the templates tell the user 29 and stay clear of it. */
export const SNAME_MAX = 29;

/** Placeholders the TEMPLATE writes. Michael's own blank templates mark fields with two underscores; same
 *  convention, so someone who has seen his files recognises these. */
const ICAO = "__ICAO__";
const AIRPORT_NAME = "__AIRPORT_NAME__";
const COUNTRY = "__COUNTRY__";

/** What makes a heliport an AIRPORT rather than a template: the identity a user types into "Create
 *  heliport…". PCT still does not invent any of it — but it does refuse a bad one (validateIdentity) and,
 *  at the write boundary, a code already present on the machine, which the hand-written route cannot do. */
export interface HeliportIdentity {
  icao: string; // 4-6 chars, lowercase [a-z0-9]
  name: string; // shown in LOCATION; <= SNAME_MAX
  country: string; // two lowercase letters — ALSO a path segment, so it is validated, not trusted
}

export type IdentityProblem =
  | "icao-format"
  | "name-empty"
  | "name-too-long"
  | "country-format";

const ICAO_RE = /^[a-z0-9]{4,6}$/;
const COUNTRY_RE = /^[a-z]{2}$/;

/** The single source of truth for "is this identity writable", used by the dialog for live feedback AND
 *  by main before it touches disk. Availability of the CODE is a separate, machine-dependent question —
 *  see main/icaoIndex.ts — because it cannot be answered from the string alone.
 *
 *  `country` gets the strictest rule of the three and it is not cosmetic: it becomes a directory name
 *  under scenery/airports/, so anything but two letters is a path-traversal question, not a typo. */
export function validateIdentity(id: HeliportIdentity): IdentityProblem | null {
  if (!ICAO_RE.test(id.icao)) return "icao-format";
  const name = sanitizeValue(id.name).trim();
  if (name.length === 0) return "name-empty";
  if (name.length > SNAME_MAX) return "name-too-long";
  if (!COUNTRY_RE.test(id.country)) return "country-format";
  return null;
}

/** The folder an installed heliport gets under `scenery/airports/<country>/`, derived from the identity
 *  the user just typed: `<code>_<name>`, which is IPACS's own convention there
 *  (`de0451_steyerberg_auxiliary_helicopter_base`).
 *
 *  It deliberately does NOT reuse the POI's folder name. That name carries a coordinate prefix, which
 *  means nothing in an airports tree — and, more to the point, it needs `project.poiName`, which a fresh
 *  project does not have: the first heliport built from an unnamed project produced `w07055s3345_` and was
 *  refused at the write boundary with a message written for a programmer. The identity is validated
 *  before we get here, so this is always a safe name (see isSafeAirportFolderName). */
export function heliportFolderName(id: HeliportIdentity): string {
  const slug = sanitizeValue(id.name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60);
  return slug === "" ? id.icao : `${id.icao}_${slug}`;
}

/** True if `name` is a safe folder to create or delete inside `scenery/airports/<country>/`. Deliberately
 *  simpler than the POI rule (which also pins the coordinate prefix): no dots at all, so no `..`, and no
 *  separators — while still accepting a folder written by an earlier build, whose name was the POI slug. */
export function isSafeAirportFolderName(name: string): boolean {
  return /^[a-z0-9_]{1,80}$/.test(name);
}

/** English, user-facing, one line — the dialog shows it and main returns it. */
export function identityProblemText(p: IdentityProblem): string {
  switch (p) {
    case "icao-format":
      return "The airport code must be 4 to 6 letters or digits.";
    case "name-empty":
      return "Enter a name for the heliport.";
    case "name-too-long":
      return `The name must be ${SNAME_MAX} characters or fewer — Aerofly drops the whole airport above its limit.`;
    case "country-format":
      return "The country code must be exactly two letters (us, de, cl…).";
  }
}

/** Everything the two files need, all of it already resolved by planExport (positions SHIFTED, height
 *  resolved) so this module is pure formatting. */
export interface HeliportSpec {
  /** Pad centre, degrees — the placed object the user picked, or the POI's anchor. */
  position: LonLat;
  /** TRUE compass degrees. Written verbatim: the sim's `heading` field is true (gate 2026-07-31). */
  headingDeg: number;
  /** Pad radius in METRES (the sim shows the diameter as "Size"). */
  radiusM: number;
  /** The POI's cultivation basename ("poi"), or null for an empty POI — then no cultivation is referenced. */
  cultivationFileName: string | null;
  /** The plant anchor, when the POI carries one — it must be repeated here, because the `.tsc` REPLACES
   *  the `poi.tsl` as the entry point and the anchor lives in the .tsl. Null → no objects block. */
  anchor: Anchor | null;
  /** The project's height mode, mirrored onto the cultivation reference. */
  autoheight: boolean;
  /** null → the TEMPLATE: `__PLACEHOLDER__` identity and the four manual steps at the top. Set → a real
   *  airport PCT is about to install itself. Same tags either way; only the values and the header differ,
   *  so there is exactly one description of this format in the codebase. */
  identity?: HeliportIdentity | null;
}

/** The three identity values as they go into the files: the real ones, or the placeholders.
 *
 *  ★ THE CODE GOES IN CAPITALS, the disk stays lowercase. ApfelFlieger, forum #172: the
 *  `<[…][icao][ABCD]>` rows in BOTH files "must be entered as capital letters in order to be displayed
 *  correctly in FS 4", while "there are only lowercase letters in the file name and in the folder name".
 *  IPACS's own files say the same thing without being asked — `de0025_osnabrueck_hospital_helipad`
 *  carries `<[stringt8c][icao][DE0025]>` next to `<[stringt8c][country][de]>`, in a folder of lowercase
 *  `de0025.*`. So: code up, country down, filenames down.
 *
 *  Why it survived v1.1 and v1.2. The sim matches codes CASE-INSENSITIVELY — that is how the heliport
 *  flew on 2026-07-31 and how icaoIndex counts the same 8139 airports the sim does — so a lowercase code
 *  costs nothing structural. What it costs is DISPLAY, which is the one symptom we had and filed under
 *  "that is Aerofly, not you": the blank row in LOCATION's search. That is now the first suspect, and it
 *  reads off one install without flying — see the note in the dialog. */
function identityValues(spec: HeliportSpec): { icao: string; name: string; country: string } {
  const id = spec.identity ?? null;
  if (id === null) return { icao: ICAO, name: AIRPORT_NAME, country: COUNTRY };
  return { icao: id.icao.toUpperCase(), name: sanitizeValue(id.name).trim(), country: id.country };
}

/** The `// Informations:` banner, sitting just INSIDE the place block (ApfelFlieger, forum #167 — the
 *  shape IPACS uses in its own aircraft files, which he asked PCT to copy). It replaces the trailing
 *  `//` comments v1.1 hung off each tag line, for two reasons he gave:
 *
 *    • TABS. v1.1 separated tag from comment with `\t\t`. Jan (IPACS) told him to prefer spaces —
 *      "TAB characters could lead to interference" — so nothing here emits one.
 *    • WIDTH. A 130-column line whose first 40 characters are the value is unreadable in the editor
 *      people actually open these in.
 *
 *  GRAMMAR, checked rather than assumed. Nothing may precede the root `<[file]` (see NO_HEADER), so the
 *  banner had to go inside something — and standalone `//` lines inside a block are not something the
 *  2026-07-31 gate covered. IPACS's own shipped files settle it: 1776 files under `aircraft/` carry
 *  standalone `//` lines, `base/system.tmd` has one four lines into a `pointer_list_tmuniverse` with a
 *  blank line above it, and 1557 of the 1569 `.tsc` under `scenery/airports/` contain blank lines. So
 *  both ingredients are load-bearing in files the sim reads every launch.
 *
 *  ★ The residual, stated because it is not zero: none of those 1569 `.tsc` uses a standalone comment —
 *  the combination is inferred from one shared grammar, not observed in this file type. It reads out of
 *  tm.log in seconds (a refused place logs `ERROR: (error loading '…/<icao>.tsc')` and the airport is in
 *  the database but cannot be flown), so it wants that check on the first install after this change. */
function informationsBanner(): string[] {
  return [
    "",
    "//  Informations:",
    `//  [icao]:     4-6 characters, IN CAPITALS here - FS 4 displays the airport by this row. It`,
    "//              MUST NOT already exist on the machine that installs this - a repeat silently",
    "//              REPLACES that airport. The file and folder names stay lowercase",
    `//  [sname]:    the name shown in LOCATION. MAX ${SNAME_MAX} CHARACTERS - longer and the sim`,
    "//              drops the whole airport",
    "//  [lname]:    long name; keep it the same unless you have a reason",
    "//  [country]:  two letters, lowercase (the 2-digit internet country code is recommended)",
    "//  [position]: lon lat in degrees - written by PCT",
    "//  [filename]: the POI's own poi.toc, right beside this file",
    "//  [radius]:   maximum rotor radius in metres - the sim shows the DIAMETER as \"Size\"",
    "//  [heading]:  TRUE heading in degrees, the sim displays magnetic, so expect this minus",
    "//              the local variation",
    "",
  ];
}

/** `heliport.tsc.txt` — the place: identity, the functional pad, and the pointer to the POI's own `poi.toc`. */
export function buildHeliportTsc(spec: HeliportSpec): string {
  const pos = `${fmtLonLat(spec.position.lon)} ${fmtLonLat(spec.position.lat)}`;
  const v = identityValues(spec);
  // `icao` first: ApfelFlieger's own standard, and the field a reader is looking for ("I put the line
  // <[string8u][icao][....]> up, because that is more logical for me"). The sim does not care about tag
  // order — its parser is name-keyed — and every field is described in the banner above.
  const body: string[] = [
    ...informationsBanner(),
    tag("string8u", "icao", v.icao),
    tag("string8", "sname", v.name),
    tag("string8", "lname", v.name),
    tag("string8u", "country", v.country),
    tag("string8u", "coordinate_system", "flat"),
    tag("vector2_float64", "position", pos),
    tag("bool", "autoheight", "true"),
  ];

  const pad = [
    tag("string8", "name", "FATO/TLOF"),
    tag("vector2_float64", "position", pos),
    tag("float64", "radius", fmtNum(spec.radiusM)),
    tag("float64", "heading", fmtNum(spec.headingDeg)),
  ];
  body.push(
    ...block("list_tmsimulator_helipad", "helipads", "", block("tmsimulator_helipad", "element", "0", pad)),
  );

  if (spec.anchor !== null) body.push(...anchorObjects(spec.anchor));

  if (spec.cultivationFileName !== null) {
    const cultivation = [
      tag("string8", "filename", spec.cultivationFileName),
      tag("bool", "auto_height", spec.autoheight ? "true" : "false"),
      tag("bool", "use_height_offset", "true"),
    ];
    body.push(
      ...block(
        "list_tmsimulator_scenery_cultivation",
        "cultivation_files",
        "",
        block("tmsimulator_scenery_cultivation", "element", "0", cultivation),
      ),
    );
  }

  const place = block("tmsimulator_scenery_place", "", "", body);
  return tidy([...NO_HEADER, ...block("file", "", "", place)]);
}

/** Join the lines and strip trailing spaces. `block` indents EVERY line it is given, including the empty
 *  ones framing the banner — which would otherwise ship as eight spaces of invisible whitespace. Applied
 *  only here, never in `block` itself: the `.tsl`/`.toc` byte-goldens depend on that helper unchanged. */
function tidy(lines: string[]): string {
  return lines.join("\n").replace(/[ \t]+$/gm, "") + "\n";
}

/** The `.wad`'s own banner. Same reasoning as the `.tsc`'s (spaces, not TABs; a block rather than
 *  trailing comments) — and the two files are read side by side, so they should read alike. The one
 *  thing worth saying twice is the position: it is the field a reader will assume is degrees. */
const WAD_BANNER: string[] = [
  "",
  "//  Informations:",
  "//  [icao]:      the SAME code as in the .tsc, IN CAPITALS - or the database entry and the place",
  "//               do not meet. The file name stays lowercase",
  "//  [name]:      max 32 characters here",
  "//  [country]:   two letters, lowercase - as in the .tsc",
  "//  [position]:  FS4 grid units (0-65536), NOT degrees - written by PCT",
  "//  [radius]:    metres, as in the .tsc",
  "//  [direction]: RADIANS here, not degrees - written by PCT",
  "",
];

/** `heliport.wad.txt` — the entry in FS4's world airport database: what puts the heliport on the map, in
 *  the flight planner and in "nearest". Its coordinates are NOT degrees; they are the projected 0–65536
 *  grid (core/geo/wad.ts), which is the tedious part PCT is here to do. */
export function buildHeliportWad(spec: HeliportSpec): string {
  const pos = `${formatWad(lonToWad(spec.position.lon))} ${formatWad(latToWad(spec.position.lat))}`;
  const pad = [
    tag("string8", "name", "FATO/TLOF"),
    tag("vector2_float64", "position", pos),
    tag("float64", "radius", fmtNum(spec.radiusM)),
    // The .wad stores the same rotation as the .toc, in RADIANS — hence the trip through headingToDirection.
    tag("float64", "direction", formatWad(directionToWad(headingToDirection(spec.headingDeg)))),
  ];
  const v = identityValues(spec);
  const body = [
    ...WAD_BANNER,
    tag("uint64", "uid", "0"),
    tag("stringt8c", "icao", v.icao),
    tag("stringt8c", "iata", ""),
    tag("stringt8c", "name", v.name),
    tag("stringt8c", "country", v.country),
    tag("vector2_float64", "position", pos),
    ...block(
      "list_tmworld_airport_detailed_helipad",
      "helipads",
      "",
      block("tmworld_airport_detailed_helipad", "element", "0", pad),
    ),
  ];
  const airport = block("tmworld_airport_detailed", "", "", body);
  return tidy([...NO_HEADER, ...block("file", "", "", airport)]);
}

/** The anchor object, repeated from the `.tsl` because the `.tsc` replaces it as the entry point. Written
 *  ABSOLUTE (the shape gated 2026-07-31 — the POI's palms stayed steady), in the tag spelling the Hong Kong
 *  community `.tsc` uses inside this same place type. */
function anchorObjects(anchor: Anchor): string[] {
  const children = [
    tag("string8", "type", "object"),
    tag("string8", "geometry", ANCHOR_GEOMETRY),
    tag(
      "tmvector3d",
      "position",
      `${fmtLonLat(anchor.position.lon)} ${fmtLonLat(anchor.position.lat)} ${anchor.heightAsl.toFixed(2)}`,
    ),
  ];
  return block(
    "tmsimulator_scenery_objecttmslist",
    "objects",
    "",
    block("tmsimulator_scenery_object", "element", "0", children),
  );
}

/** ★ NOTHING may precede the root `<[file]` tag. The sim's parser rejects the WHOLE file — the only
 *  symptom is `ERROR: (error loading '…/<icao>.tsc')` in tm.log and an airport that is in the database
 *  (its `.wad` loaded) but has no place, so it half-appears and cannot be flown.
 *
 *  Measured 2026-07-31: the same file WITH a ten-line `//` banner above `<[file]` failed to load, and
 *  without it flew. Both known-good heliports agree — ApfelFlieger's `de0869.tsc` and the Hong Kong
 *  community pack both start on `<[file][][]`. TRAILING `//` comments on a tag line are fine: the file
 *  that flew is full of them.
 *
 *  So the human instructions live in README.txt, which is a human file, and these stay pure format.
 *  (PCT's own tmParser was taught to skip a leading banner while chasing this — do not read that as
 *  permission: the parser that matters is the sim's, and it was never taught anything.) */
const NO_HEADER: string[] = [];

/** Marker in an installed heliport's README.txt. Same trick as POI_README_MARKER: it is what makes a
 *  folder under scenery/airports/ safe to offer for Uninstall — PCT removes only what PCT wrote. */
export const HELIPORT_README_MARKER = "Installed by PCT (POI Creation Tool) - heliport";

/** README.txt for an INSTALLED heliport. */
export function heliportInstalledReadme(id: HeliportIdentity, projectName: string): string {
  return [
    `${sanitizeValue(projectName).trim()} - heliport ${id.icao.toUpperCase()}`,
    HELIPORT_README_MARKER,
    "",
    "Restart Aerofly after installing - airports are read once, at startup.",
    "",
    `Then open LOCATION and search for "${sanitizeValue(id.name).trim()}" - by NAME. The search does`,
    "not match the airport code, and the row it finds may render blank: Aerofly takes the text it shows",
    "there from its own world database, which knows nothing about a code you invented. The airport is",
    "real all the same - it shows correctly on the map, where you built it, and it flies.",
    "",
    "This folder holds the airport itself; the objects come from the poi.toc beside it, which is",
    "the same cultivation the POI export writes.",
    "",
    "About the airport code: if two airports on one machine share a code, ONE of them wins and the",
    `other vanishes, leaving only a line in tm.log. "${id.icao.toUpperCase()}" was checked against every`,
    "airport installed on this machine at the moment this was written. That check cannot speak for",
    "anyone else's machine - if you pass this folder on, the code has to be free there too.",
    "",
    "To remove it: PCT's Install HELIPORT dialog lists installed heliports with an Uninstall button,",
    "or just delete this folder. Nothing outside it was touched.",
    "",
  ].join("\n");
}

/** The lines README.txt gains when the templates ship. The steps live HERE and not inside the two files
 *  because nothing may precede the root tag of a `.tsc` (see NO_HEADER) — and these files become a `.tsc`
 *  the moment the user finishes step 3. */
export function heliportReadmeLines(): string[] {
  return [
    "HELIPORT TEMPLATE (advanced)",
    "",
    `  ${HELIPORT_TSC_FILE} and ${HELIPORT_WAD_FILE} turn this POI into a heliport you`,
    "  can start a flight from. Aerofly ignores them as they are. To finish them by hand:",
    "",
    "   1. Move this whole folder out of  scenery/poi/  and into  scenery/airports/",
    "      A layout that works:  scenery/airports/<country>/<this folder>/",
    `   2. Replace ${ICAO}, ${AIRPORT_NAME} and ${COUNTRY} in BOTH files.`,
    "      The code must be 4-6 characters and FREE on the machine that installs this: an existing",
    "      code REPLACES that airport, leaving only a line in tm.log. Check it in Aerofly's LOCATION",
    `      menu first. The name must be ${SNAME_MAX} characters or fewer, or the airport is dropped whole.`,
    "      Type the code IN CAPITALS inside both files - FS 4 displays the airport by that row.",
    "   3. Rename both files to  <code>.tsc  and  <code>.wad  - dropping the .txt. These two go in",
    "      LOWERCASE, like every other file name under scenery/airports.",
    "   4. Delete poi.tsl. The .tsc takes its place. Keep poi.toc and any pct_anchor files.",
    "",
    "  Do not add anything above the first  <[file]  line of either file: Aerofly refuses to load a",
    "  .tsc that does not start with it, and says so only in tm.log.",
    "",
    "  PCT can do all of this for you - see Install HELIPORT in the app.",
    "",
  ];
}
