// heliportTemplate.ts — the POI's optional `heliport.tsc.txt` / `heliport.wad.txt` pair: two TEMPLATES a
// user can turn into a real AFS4 heliport by hand (forum #160, ApfelFlieger).
//
// WHY TEMPLATES AND NOT AN AIRPORT. A user `.tsc` whose `icao` collides with a base airport SILENTLY
// REPLACES it — the only trace is one line in tm.log — and POIs get shared, so PCT cannot validate an
// ICAO on a machine it has never seen. That is the whole reason PCT does not write airports. These files
// dodge it by construction:
//
//   • PCT never picks an identity. `icao` / `name` / `country` ship as `__PLACEHOLDER__` text; the person
//     who fills them in is the same person who moves the folder into scenery/airports.
//   • The `.txt` suffix makes them INERT wherever they sit. (Measured 2026-07-31: a `.tsc`+`.wad` dropped
//     into scenery/poi/ is not read AT ALL — the sim's `airports=` count did not move and the 36-char
//     `sname` that makes it log `airport name … too long` for files under scenery/airports/ stayed silent.
//     So even the bare names were safe; `.txt` costs the user nothing — Michael's own recipe already ends
//     in "rename the files to the airport code" — and it survives a sim update changing that.)
//
// PROVENANCE. Every tag, and the order, is copied from a heliport that WORKS: ApfelFlieger's `de0869`
// (forum #113 / thread 28713 #78), then flown end-to-end at KDAG on 2026-07-31 with these exact contents
// generated by hand. That gate settled the open questions this file used to have to guess:
//
//   `coordinate_system` = `flat` loads · `uid` 0 is fine · `airports/<continent>/<country>/<name>/` works ·
//   `radius` is METRES (the sim's own panel showed "Size 66 ft / 20 m" for radius 10) · `heading` is TRUE
//   degrees (we wrote 40, the sim showed 028 = 40 − the local magnetic variation) — so PCT's stored true
//   heading goes in verbatim, no conversion · the `objects` block below, in the `tmsimulator_scenery_objecttmslist`
//   spelling taken from the Hong Kong community pack, DOES reach the cultivation (the POI's palms did not blink).

import type { LonLat } from "../project/types";
// No sanitizeValue here on purpose: every value these templates write is either a PCT-formatted number or
// one of our own literals (the `__PLACEHOLDER__` identity fields). Nothing user-typed reaches them — which
// is exactly the property that keeps PCT out of the ICAO business.
import { tag, block, fmtLonLat, fmtNum } from "../tm/tmEmit";
import { lonToWad, latToWad, directionToWad, formatWad } from "../geo/wad";
import { headingToDirection } from "../geo/orientation";
import { ANCHOR_GEOMETRY, type Anchor } from "./plantAnchor";

/** The two template filenames. `.txt` on purpose (see the header); the user renames them to `<icao>.tsc`
 *  and `<icao>.wad`, which their recipe has them doing anyway. */
export const HELIPORT_TSC_FILE = "heliport.tsc.txt";
export const HELIPORT_WAD_FILE = "heliport.wad.txt";

/** Longest `sname` the sim accepts. It REJECTS THE WHOLE AIRPORT above the limit, with
 *  `ERROR: (airport name '…' too long. tsc='…')` — three of IPACS's own files trip it. The exact cut is
 *  somewhere in [30, 34] (30 loads, 35 fails), so the templates tell the user 29 and stay clear of it. */
export const SNAME_MAX = 29;

/** Placeholders the user replaces. Michael's own blank templates mark fields with two underscores; same
 *  convention, so someone who has seen his files recognises these. */
const ICAO = "__ICAO__";
const AIRPORT_NAME = "__AIRPORT_NAME__";
const COUNTRY = "__COUNTRY__";

/** Everything the two files need, all of it already resolved by planExport (positions SHIFTED, height
 *  resolved) so this module is pure formatting. */
export interface HeliportSpec {
  /** Pad centre, degrees — the placed object the user picked, or the POI's anchor. */
  position: LonLat;
  /** TRUE compass degrees. Written verbatim: the sim's `heading` field is true (gate 2026-07-31). */
  headingDeg: number;
  /** Pad radius in METRES (the sim shows the diameter as "Size"). */
  radiusM: number;
  /** The POI's cultivation basename ("poi"), or null for an empty POI — then no cultivation is referenced. */
  cultivationFileName: string | null;
  /** The plant anchor, when the POI carries one — it must be repeated here, because the `.tsc` REPLACES
   *  the `poi.tsl` as the entry point and the anchor lives in the .tsl. Null → no objects block. */
  anchor: Anchor | null;
  /** The project's height mode, mirrored onto the cultivation reference. */
  autoheight: boolean;
}

/** `heliport.tsc.txt` — the place: identity, the functional pad, and the pointer to the POI's own `poi.toc`. */
export function buildHeliportTsc(spec: HeliportSpec): string {
  const pos = `${fmtLonLat(spec.position.lon)} ${fmtLonLat(spec.position.lat)}`;
  const body: string[] = [
    `${tag("string8", "sname", AIRPORT_NAME)}\t\t// the name shown in LOCATION. MAX ${SNAME_MAX} CHARACTERS - longer and the sim drops the whole airport.`,
    `${tag("string8", "lname", AIRPORT_NAME)}\t\t// long name; keep it the same unless you have a reason.`,
    `${tag("string8u", "icao", ICAO)}\t\t// 4-6 characters, and it MUST NOT already exist on the machine that installs this. A repeat silently REPLACES that airport.`,
    `${tag("string8u", "country", COUNTRY)}\t\t// two letters, lowercase: us, de, cl`,
    tag("string8u", "coordinate_system", "flat"),
    `${tag("vector2_float64", "position", pos)}\t\t// degrees, lon lat - written by PCT`,
    tag("bool", "autoheight", "true"),
  ];

  const pad = [
    tag("string8", "name", "FATO/TLOF"),
    `${tag("vector2_float64", "position", pos)}\t\t// written by PCT`,
    `${tag("float64", "radius", fmtNum(spec.radiusM))}\t\t// METRES`,
    `${tag("float64", "heading", fmtNum(spec.headingDeg))}\t\t// TRUE degrees. The sim displays magnetic, so expect this minus the local variation.`,
  ];
  body.push(
    ...block("list_tmsimulator_helipad", "helipads", "", block("tmsimulator_helipad", "element", "0", pad)),
  );

  if (spec.anchor !== null) body.push(...anchorObjects(spec.anchor));

  if (spec.cultivationFileName !== null) {
    const cultivation = [
      `${tag("string8", "filename", spec.cultivationFileName)}\t\t// the POI's own poi.toc, right beside this file`,
      tag("bool", "auto_height", spec.autoheight ? "true" : "false"),
      tag("bool", "use_height_offset", "true"),
    ];
    body.push(
      ...block(
        "list_tmsimulator_scenery_cultivation",
        "cultivation_files",
        "",
        block("tmsimulator_scenery_cultivation", "element", "0", cultivation),
      ),
    );
  }

  const place = block("tmsimulator_scenery_place", "", "", body);
  return [...INSTRUCTIONS, ...block("file", "", "", place)].join("\n") + "\n";
}

/** `heliport.wad.txt` — the entry in FS4's world airport database: what puts the heliport on the map, in
 *  the flight planner and in "nearest". Its coordinates are NOT degrees; they are the projected 0–65536
 *  grid (core/geo/wad.ts), which is the tedious part PCT is here to do. */
export function buildHeliportWad(spec: HeliportSpec): string {
  const pos = `${formatWad(lonToWad(spec.position.lon))} ${formatWad(latToWad(spec.position.lat))}`;
  const pad = [
    tag("string8", "name", "FATO/TLOF"),
    `${tag("vector2_float64", "position", pos)}\t\t// written by PCT`,
    `${tag("float64", "radius", fmtNum(spec.radiusM))}\t\t// METRES`,
    // The .wad stores the same rotation as the .toc, in RADIANS — hence the trip through headingToDirection.
    `${tag("float64", "direction", formatWad(directionToWad(headingToDirection(spec.headingDeg))))}\t\t// RADIANS here, not degrees - written by PCT`,
  ];
  const body = [
    tag("uint64", "uid", "0"),
    `${tag("stringt8c", "icao", ICAO)}\t\t// the SAME code as in the .tsc`,
    tag("stringt8c", "iata", ""),
    `${tag("stringt8c", "name", AIRPORT_NAME)}\t\t// max 32 characters here`,
    tag("stringt8c", "country", COUNTRY),
    `${tag("vector2_float64", "position", pos)}\t\t// FS4 grid units (0-65536), NOT degrees - written by PCT`,
    ...block(
      "list_tmworld_airport_detailed_helipad",
      "helipads",
      "",
      block("tmworld_airport_detailed_helipad", "element", "0", pad),
    ),
  ];
  const airport = block("tmworld_airport_detailed", "", "", body);
  return [...INSTRUCTIONS, ...block("file", "", "", airport)].join("\n") + "\n";
}

/** The anchor object, repeated from the `.tsl` because the `.tsc` replaces it as the entry point. Written
 *  ABSOLUTE (the shape gated 2026-07-31 — the POI's palms stayed steady), in the tag spelling the Hong Kong
 *  community `.tsc` uses inside this same place type. */
function anchorObjects(anchor: Anchor): string[] {
  const children = [
    tag("string8", "type", "object"),
    tag("string8", "geometry", ANCHOR_GEOMETRY),
    tag(
      "tmvector3d",
      "position",
      `${fmtLonLat(anchor.position.lon)} ${fmtLonLat(anchor.position.lat)} ${anchor.heightAsl.toFixed(2)}`,
    ),
  ];
  return block(
    "tmsimulator_scenery_objecttmslist",
    "objects",
    "",
    block("tmsimulator_scenery_object", "element", "0", children),
  );
}

/** The four manual steps, repeated at the top of BOTH files — whichever one the user opens first tells
 *  them the whole procedure. `//` comments are part of the format (IPACS's own text files carry them). */
const INSTRUCTIONS: string[] = [
  "// ---------------------------------------------------------------------------",
  "// HELIPORT TEMPLATE - written by PCT. Aerofly does NOT read this file as it is.",
  "//",
  "// To turn this POI into a heliport you can start a flight from:",
  "//",
  "//   1. Move this whole folder out of  scenery/poi/  and into  scenery/airports/",
  "//      (a layout that works: scenery/airports/<continent>/<country>/<this folder>/ )",
  `//   2. Replace ${ICAO}, ${AIRPORT_NAME} and ${COUNTRY} in BOTH files.`,
  "//      Check the code is free FIRST: start Aerofly, open LOCATION and search for it.",
  "//      An ICAO that already exists REPLACES that airport, and the only trace is one line in tm.log.",
  "//   3. Rename both files to  <icao>.tsc  and  <icao>.wad  (drop the .txt).",
  "//   4. Delete poi.tsl - this .tsc takes its place. Keep poi.toc and any pct_anchor files.",
  "//",
  "// Then restart Aerofly: the heliport is in the LOCATION menu, and every object you placed",
  "// in PCT is around the pad.",
  "// ---------------------------------------------------------------------------",
  "",
];

/** The lines README.txt gains when the templates ship, so the POI folder explains itself. */
export function heliportReadmeLines(): string[] {
  return [
    "Heliport template (advanced):",
    `  ${HELIPORT_TSC_FILE} + ${HELIPORT_WAD_FILE} turn this POI into a heliport you can`,
    "  start a flight from. Aerofly ignores them as they are - open either one, the steps are at the top.",
    "",
  ];
}
