// planExport.ts — Project + height-resolved objects → a pure ExportPlan (design §3.4).
//
// No I/O: it returns { folderName, files[], warnings } describing exactly what the installer
// (main process, M1b) should write into `scenery/poi/<folderName>/`. Keeping this pure makes
// the whole POI package golden-testable byte-for-byte, the way the Race App exporter was.

import type { ExportPlan, LonLat, PoiFile, Project, ResolvedObject } from "../project/types";
import { centroid, poiFolderName } from "../geo/poiName";
import { shiftEastNorth } from "../geo/geo";
import { directionToHeading } from "../geo/orientation";
import { buildToc } from "./tocWriter";
import { buildTsl } from "./tslWriter";
import { computeAnchor, computeAutoheightAnchor, ANCHOR_ASSETS } from "./plantAnchor";
import {
  buildHeliportTsc,
  buildHeliportWad,
  heliportReadmeLines,
  HELIPORT_TSC_FILE,
  HELIPORT_WAD_FILE,
} from "./heliportTemplate";

// A POI's two payload files are named `poi.tsl` / `poi.toc` (format bible), and the .tsl
// references the .toc by this basename.
const POI_BASENAME = "poi";

/** Marker line dropped in README.txt so the installer can tell PCT-made POIs apart from
 *  hand-made or third-party ones when listing/uninstalling (design §3.4 `byPct`). */
export const POI_README_MARKER = "Generated by PCT (POI Creation Tool)";

function buildReadme(project: Project, resolved: ResolvedObject[], heliport: boolean): string {
  return [
    project.name,
    POI_README_MARKER,
    "",
    `Objects: ${resolved.length}`,
    "",
    "Install: copy this whole folder (keep its name) into your Aerofly FS 4 user",
    "folder's scenery/poi/ , then restart Aerofly FS 4 and fly to the area:",
    "  Windows: Documents\\Aerofly FS 4\\scenery\\poi\\",
    "  macOS:   ~/Library/Application Support/Aerofly FS 4/scenery/poi/",
    "",
    ...(heliport ? heliportReadmeLines() : []),
  ].join("\n");
}

/** Opt-in heliport templates (forum #160). The user names the PAD, not an airport: `objectId` is the
 *  placed object whose position and heading it takes — null (or an id that isn't in the scene) falls back
 *  to the POI's own anchor point. Everything about identity stays a placeholder; see heliportTemplate.ts. */
export interface HeliportOptions {
  objectId: string | null;
  radiusM: number; // metres
}

/** The pad's position and TRUE heading. Reads them off the SHIFTED object so the pad lands with the
 *  scene, not `shift` metres away from it — the same trap the folder-name preview had to be fixed for.
 *  Only the kinds that HAVE a facing contribute one; a plant is a billboard and a point light has no
 *  front, so those (and the anchor fallback) give a pad pointing true north. */
function heliportPad(
  objects: ResolvedObject[],
  fallback: LonLat,
  objectId: string | null,
): { position: LonLat; headingDeg: number; found: boolean } {
  const pick = objectId === null ? undefined : objects.find((o) => o.id === objectId);
  if (pick === undefined) return { position: fallback, headingDeg: 0, found: objectId === null };
  const headingDeg =
    pick.kind === "xref"
      ? directionToHeading(pick.direction)
      : pick.kind === "airport_light"
        ? pick.orientation // already a compass heading (see PlacedAirportLight)
        : 0;
  return { position: pick.position, headingDeg, found: true };
}

/** Plan the POI package. `project.reference` sets the folder-name anchor; when null it falls
 *  back to the centroid of the placed objects (design §2.2). */
/** Apply the project's global export shift (forum #12) to every object's position: nudge each one
 *  `shift` metres east/north. The height was resolved at the object's REAL location, so shifting the
 *  horizontal coordinate afterwards is correct — it only lines the objects up with FS4's satellite
 *  tiles. A zero/absent shift returns the same array (no-op), keeping the golden output stable. */
function applyShift(resolved: ResolvedObject[], shift: Project["shift"]): ResolvedObject[] {
  if (!shift || (shift.east === 0 && shift.north === 0)) return resolved;
  return resolved.map((o) => ({ ...o, position: shiftEastNorth(o.position, shift.east, shift.north) }));
}

export function planExport(
  project: Project,
  resolved: ResolvedObject[],
  opts: { heliport?: HeliportOptions } = {},
): ExportPlan {
  const warnings: string[] = [];
  if (resolved.length === 0) {
    warnings.push("The POI has no objects — nothing will appear in the sim.");
  }

  const autoheight = project.heightMode === "autoheight";
  const objects = applyShift(resolved, project.shift);
  const ref = project.reference ?? centroid(objects.map((o) => o.position));
  const folderName = poiFolderName(ref, project.poiName);
  const tocFileName = objects.length > 0 ? POI_BASENAME : null;
  // The reference-POI anchor (plantAnchor.ts): the anchor object emitted in the .tsl plus its bundled
  // mesh/texture assets. In AUTOHEIGHT mode every non-empty POI carries it (computed from ALL objects — it
  // is what makes autoheight reach the cultivation); in BAKED-ASL only a POI with plants does (to stop them
  // blinking). Computed from the SHIFTED objects so it lines up with them; null ⇒ no anchor and no assets.
  const anchor = autoheight ? computeAutoheightAnchor(objects) : computeAnchor(objects);

  const files: PoiFile[] = [
    { relPath: `${POI_BASENAME}.tsl`, content: buildTsl({ tocFileName, anchor, autoheight }) },
    { relPath: `${POI_BASENAME}.toc`, content: buildToc(objects) },
    { relPath: "README.txt", content: buildReadme(project, objects, opts.heliport !== undefined) },
  ];

  if (opts.heliport !== undefined) {
    const pad = heliportPad(objects, ref, opts.heliport.objectId);
    if (!pad.found) {
      warnings.push(
        "The object chosen for the helipad is no longer in the scene — the pad was placed at the POI's anchor point instead.",
      );
    }
    if (autoheight) {
      // Emitted, not blocked: the templates were only ever FLOWN in baked-asl (2026-07-31), and the flag
      // they mirror onto the cultivation reference is untested in this container. Say so rather than
      // pretend, and rather than refuse something that may well work.
      warnings.push(
        "The heliport template was only verified in-sim with baked-asl heights — in Sim-autoheight mode, check the objects' heights after the first flight.",
      );
    }
    const spec = {
      position: pad.position,
      headingDeg: pad.headingDeg,
      radiusM: opts.heliport.radiusM,
      cultivationFileName: tocFileName,
      anchor,
      autoheight,
    };
    files.push(
      { relPath: HELIPORT_TSC_FILE, content: buildHeliportTsc(spec) },
      { relPath: HELIPORT_WAD_FILE, content: buildHeliportWad(spec) },
    );
  }

  return { folderName, files, assets: anchor ? [...ANCHOR_ASSETS] : [], warnings };
}
