// planExport.ts — Project + height-resolved objects → a pure ExportPlan (design §3.4).
//
// No I/O: it returns { folderName, files[], warnings } describing exactly what the installer
// (main process) should write into `scenery/poi/<folderName>/`. Keeping this pure makes
// the whole POI package golden-testable byte-for-byte.

import type {
  AirportAerotow,
  AirportPad,
  AirportParking,
  AirportRunway,
  AirportWinch,
  ExportPlan,
  LonLat,
  PoiFile,
  Project,
  ResolvedObject,
} from "../project/types";
import { centroid, poiFolderName } from "../geo/poiName";
import { shiftEastNorth } from "../geo/geo";
import { buildToc } from "./tocWriter";
import { buildTsl } from "./tslWriter";
import { computeAnchor, computeAutoheightAnchor, ANCHOR_ASSETS } from "./plantAnchor";
import {
  buildHeliportTsc,
  buildHeliportWad,
  heliportFolderName,
  heliportInstalledReadme,
  validateIdentity,
  type HeliportAerotowSpec,
  type HeliportIdentity,
  type HeliportPadSpec,
  type HeliportParkingSpec,
  type HeliportRunwayEndSpec,
  type HeliportRunwaySpec,
  type HeliportSpec,
  type HeliportWinchSpec,
  type IdentityProblem,
} from "./heliportTemplate";

// A POI's two payload files are named `poi.tsl` / `poi.toc`, and the .tsl
// references the .toc by this basename.
const POI_BASENAME = "poi";

/** Marker line dropped in README.txt so the installer can tell PCT-made POIs apart from
 *  hand-made or third-party ones when listing/uninstalling (design §3.4 `byPct`). */
export const POI_README_MARKER = "Generated by PCT (POI Creation Tool)";

function buildReadme(project: Project, resolved: ResolvedObject[]): string {
  return [
    project.name,
    POI_README_MARKER,
    "",
    `Objects: ${resolved.length}`,
    "",
    "Install: copy this whole folder (keep its name) into your Aerofly FS 4 user",
    "folder's scenery/poi/ , then restart Aerofly FS 4 and fly to the area:",
    "  Windows: Documents\\Aerofly FS 4\\scenery\\poi\\",
    "  macOS:   ~/Library/Application Support/Aerofly FS 4/scenery/poi/",
    "",
  ].join("\n");
}

/** The pad radius PCT starts from when nobody has chosen one, metres (the sim shows a 20 m "Size"),
 *  which comfortably clears an EC135's 10.2 m rotor. */
export const DEFAULT_PAD_RADIUS_M = 10;

/** What the AIRPORT install writes. Everything about IDENTITY lives beside it; see heliportTemplate.ts. */
export interface HeliportOptions {
  /** The pads, in the same UNSHIFTED map coordinates the placed objects use — the planner applies the
   *  project's export shift to them below, so a pad travels with the scene instead of ending up `shift`
   *  metres away from it.
   *
   *  EMPTY → no helipad at all, which is legal for an airport that has a runway. PCT never invents one. */
  pads: AirportPad[];
  /** The parking positions, unshifted like the pads. Absent or EMPTY → an empty `parking_positions`
   *  block.
   *
   *  There is no "empty means one default" rule here, and there must not be: an airport with no stand is
   *  simply an airport with no stand. */
  parkings?: AirportParking[];
  /** The runways, unshifted. Absent or EMPTY → an empty runway block in both files. */
  runways?: AirportRunway[];
  /** The glider starts, unshifted. Absent or EMPTY → empty blocks; `.wad`-only. */
  aerotows?: AirportAerotow[];
  winches?: AirportWinch[];
  /** The AIRPORT's own point, unshifted (independent of any pad). Absent → the first pad's position,
   *  which keeps older projects' output unchanged. */
  position?: LonLat;
}

/** Move a point by the project's export shift (no-op when absent or zero).
 *
 *  Airport parts (pads etc.) are their own points on the document (types.ts AirportPad), never derived
 *  from a placed object: a pad that borrowed a mast's coordinates would spawn the helicopter inside the
 *  mast. Seeding one from a selection is a copy the UI offers, not a link the exporter follows. */
function shiftPoint(p: LonLat, shift: Project["shift"]): LonLat {
  return !shift || (shift.east === 0 && shift.north === 0)
    ? p
    : shiftEastNorth(p, shift.east, shift.north);
}

/** The pads exactly as the project has them: shifted with the scene, nothing invented. */
function mapPads(pads: AirportPad[], shift: Project["shift"]): HeliportPadSpec[] {
  return pads.map((p) => ({
    name: p.name,
    position: shiftPoint(p.position, shift),
    headingDeg: p.heading,
    radiusM: p.radius,
  }));
}

/** The runways, shifted with the scene — BOTH points of each end, or a displaced threshold would stay
 *  behind while the pavement moved. */
function heliportRunways(
  runways: AirportRunway[] | undefined,
  shift: Project["shift"],
): HeliportRunwaySpec[] {
  return (runways ?? []).map((r) => ({
    widthM: r.width,
    ends: r.ends.map((e) => ({
      // ONE point in the document, BOTH rows in the file (types.ts AirportRunwayEnd).
      endpoint: shiftPoint(e.threshold, shift),
      threshold: shiftPoint(e.threshold, shift),
      identifier: e.identifier,
      appltsys: e.appltsys,
      papi: e.papi,
      reil: e.reil,
      approach: e.approach,
      takeoff: e.takeoff,
    })) as [HeliportRunwayEndSpec, HeliportRunwayEndSpec],
  }));
}

/** The glider starts, shifted with the scene. The winch gets BOTH of its points moved — shifting only the
 *  glider would stretch the rope instead of moving the launch. */
function heliportAerotows(
  aerotows: AirportAerotow[] | undefined,
  shift: Project["shift"],
): HeliportAerotowSpec[] {
  return (aerotows ?? []).map((a) => ({
    name: a.name,
    position: shiftPoint(a.position, shift),
    headingDeg: a.heading,
  }));
}

function heliportWinches(
  winches: AirportWinch[] | undefined,
  shift: Project["shift"],
): HeliportWinchSpec[] {
  return (winches ?? []).map((w) => ({
    name: w.name,
    position: shiftPoint(w.position, shift),
    winch: shiftPoint(w.winch, shift),
    spacingM: w.spacing,
  }));
}

/** The stands, shifted with the scene. No empty-list fallback on purpose (see HeliportOptions.parkings). */
function heliportParkings(
  parkings: AirportParking[] | undefined,
  shift: Project["shift"],
): HeliportParkingSpec[] {
  return (parkings ?? []).map((p) => ({
    name: p.name,
    position: shiftPoint(p.position, shift),
    headingDeg: p.heading,
    sizeM: p.size,
    type: p.type,
  }));
}

/** Where the airport itself goes. Its own point when the project set one, otherwise the first pad's —
 *  which keeps a project written before the two were split producing the same coordinates. */
function heliportPosition(
  opts: HeliportOptions,
  pads: HeliportPadSpec[],
  fallback: LonLat,
  shift: Project["shift"],
): LonLat {
  if (opts.position !== undefined) return shiftPoint(opts.position, shift);
  return pads[0]?.position ?? fallback;
}

/** Apply the project's global export shift to every object's position: nudge each one
 *  `shift` metres east/north. The height was resolved at the object's REAL location, so shifting the
 *  horizontal coordinate afterwards is correct — it only lines the objects up with FS4's satellite
 *  tiles. A zero/absent shift returns the same array (no-op), keeping the golden output stable. */
function applyShift(resolved: ResolvedObject[], shift: Project["shift"]): ResolvedObject[] {
  if (!shift || (shift.east === 0 && shift.north === 0)) return resolved;
  return resolved.map((o) => ({ ...o, position: shiftEastNorth(o.position, shift.east, shift.north) }));
}

/** Plan the POI package — three files, always the same three. `project.reference` sets the
 *  folder-name anchor; when null it falls back to the centroid of the placed objects.
 *
 *  A POI folder never carries airport files (`.tsc`/`.wad`): an airport cannot live under scenery/poi/,
 *  and users would mistake them for a usable airfield. Airports go through `planHeliport` below. */
export function planExport(project: Project, resolved: ResolvedObject[]): ExportPlan {
  const warnings: string[] = [];
  if (resolved.length === 0) {
    warnings.push("The POI has no objects — nothing will appear in the sim.");
  }

  const autoheight = project.heightMode === "autoheight";
  const objects = applyShift(resolved, project.shift);
  const ref = project.reference ?? centroid(objects.map((o) => o.position));
  const folderName = poiFolderName(ref, project.poiName);
  const tocFileName = objects.length > 0 ? POI_BASENAME : null;
  // The reference-POI anchor (plantAnchor.ts): the anchor object emitted in the .tsl plus its bundled
  // mesh/texture assets. In AUTOHEIGHT mode every non-empty POI carries it (computed from ALL objects — it
  // is what makes autoheight reach the cultivation); in BAKED-ASL only a POI with plants does (to stop them
  // blinking). Computed from the SHIFTED objects so it lines up with them; null ⇒ no anchor and no assets.
  const anchor = autoheight ? computeAutoheightAnchor(objects) : computeAnchor(objects);

  const files: PoiFile[] = [
    { relPath: `${POI_BASENAME}.tsl`, content: buildTsl({ tocFileName, anchor, autoheight }) },
    { relPath: `${POI_BASENAME}.toc`, content: buildToc(objects) },
    { relPath: "README.txt", content: buildReadme(project, objects) },
  ];

  return { folderName, files, assets: anchor ? [...ANCHOR_ASSETS] : [], warnings };
}

/** A heliport PCT installs itself. The POI's files minus the `poi.tsl` the `.tsc` replaces, with the
 *  identity filled in and the two files named after the code. */
export interface HeliportPlan {
  folderName: string; // the POI's own slug — already a safe name, so the installer's guard applies unchanged
  country: string; // the directory under scenery/airports/ this goes in
  icao: string;
  files: PoiFile[];
  assets: string[];
  warnings: string[];
}

/** Thrown when an identity that never passed validateIdentity reaches the planner. Callers validate for
 *  the MESSAGE; this exists so no path can skip it and write a broken airport. */
export class InvalidHeliportIdentityError extends Error {
  constructor(readonly problem: IdentityProblem) {
    super(`Invalid heliport identity: ${problem}`);
    this.name = "InvalidHeliportIdentityError";
  }
}

export function planHeliport(
  project: Project,
  resolved: ResolvedObject[],
  opts: { identity: HeliportIdentity; heliport: HeliportOptions },
): HeliportPlan {
  const problem = validateIdentity(opts.identity);
  if (problem !== null) throw new InvalidHeliportIdentityError(problem);

  const warnings: string[] = [];
  const autoheight = project.heightMode === "autoheight";
  const objects = applyShift(resolved, project.shift);
  const ref = project.reference ?? centroid(objects.map((o) => o.position));
  // NOT the POI folder name: that one needs project.poiName, which a fresh project has not got, and its
  // coordinate prefix means nothing under scenery/airports/. See heliportFolderName.
  const folderName = heliportFolderName(opts.identity);
  const tocFileName = objects.length > 0 ? POI_BASENAME : null;
  const anchor = autoheight ? computeAutoheightAnchor(objects) : computeAnchor(objects);

  // The AIRPORT install writes what the project has and invents nothing.
  const pads = mapPads(opts.heliport.pads, project.shift);
  if (autoheight) {
    warnings.push(
      "Heliports were only verified in-sim with baked-asl heights — in Sim-autoheight mode, check the objects' heights after the first flight.",
    );
  }
  // ⛔ FS 4 rejects an airport with neither a runway nor a helipad (a stand or a glider start does not
  // count), so warn. PCT still never INVENTS a helipad: an airport with a runway and no helipad is legal.
  if (pads.length === 0 && (opts.heliport.runways ?? []).length === 0) {
    warnings.push(
      "Aerofly rejects an airport with no helipad and no runway — it needs at least one of the two.",
    );
  }
  if (objects.length === 0) {
    // Without a pad, "just the pad" would contradict the warning above.
    warnings.push(
      pads.length === 0
        ? "The airport has no objects around it either — this installs the bare airfield data."
        : "The heliport has no objects around it — just the pad.",
    );
  }

  const spec: HeliportSpec = {
    position: heliportPosition(opts.heliport, pads, ref, project.shift),
    pads,
    runways: heliportRunways(opts.heliport.runways, project.shift),
    aerotows: heliportAerotows(opts.heliport.aerotows, project.shift),
    winches: heliportWinches(opts.heliport.winches, project.shift),
    parkings: heliportParkings(opts.heliport.parkings, project.shift),
    cultivationFileName: tocFileName,
    anchor,
    autoheight,
    identity: opts.identity,
  };
  const icao = opts.identity.icao;
  const files: PoiFile[] = [
    { relPath: `${icao}.tsc`, content: buildHeliportTsc(spec) },
    { relPath: `${icao}.wad`, content: buildHeliportWad(spec) },
    { relPath: "README.txt", content: heliportInstalledReadme(opts.identity, project.name) },
  ];
  // No `poi.tsl`: the `.tsc` IS the place. Shipping both would load the same cultivation twice.
  if (tocFileName !== null) files.splice(2, 0, { relPath: `${POI_BASENAME}.toc`, content: buildToc(objects) });

  return {
    folderName,
    country: opts.identity.country,
    icao,
    files,
    assets: anchor ? [...ANCHOR_ASSETS] : [],
    warnings,
  };
}
