// planExport.ts — Project + height-resolved objects → a pure ExportPlan (design §3.4).
//
// No I/O: it returns { folderName, files[], warnings } describing exactly what the installer
// (main process, M1b) should write into `scenery/poi/<folderName>/`. Keeping this pure makes
// the whole POI package golden-testable byte-for-byte, the way the Race App exporter was.

import type { ExportPlan, PoiFile, Project, ResolvedXref } from "../project/types";
import { centroid, poiFolderName } from "../geo/poiName";
import { buildToc } from "./tocWriter";
import { buildTsl } from "./tslWriter";

// A POI's two payload files are named `poi.tsl` / `poi.toc` (format bible), and the .tsl
// references the .toc by this basename.
const POI_BASENAME = "poi";

/** Marker line dropped in README.txt so the installer can tell PCT-made POIs apart from
 *  hand-made or third-party ones when listing/uninstalling (design §3.4 `byPct`). */
export const POI_README_MARKER = "Generated by PCT (POI Creation Tool)";

function buildReadme(project: Project, resolved: ResolvedXref[]): string {
  return [
    project.name,
    POI_README_MARKER,
    "",
    `Objects: ${resolved.length}`,
    "",
    "Install: copy this whole folder (keep its name) into your Aerofly FS 4 user",
    "folder's scenery/poi/ , then restart Aerofly FS 4 and fly to the area:",
    "  Windows: Documents\\Aerofly FS 4\\scenery\\poi\\",
    "  macOS:   ~/Library/Application Support/Aerofly FS 4/scenery/poi/",
    "",
  ].join("\n");
}

/** Plan the POI package. `project.reference` sets the folder-name anchor; when null it falls
 *  back to the centroid of the placed objects (design §2.2). */
export function planExport(project: Project, resolved: ResolvedXref[]): ExportPlan {
  const warnings: string[] = [];
  if (resolved.length === 0) {
    warnings.push("The POI has no objects — nothing will appear in the sim.");
  }

  const ref = project.reference ?? centroid(resolved.map((o) => o.position));
  const folderName = poiFolderName(ref, project.poiName);
  const tocFileName = resolved.length > 0 ? POI_BASENAME : null;

  const files: PoiFile[] = [
    { relPath: `${POI_BASENAME}.tsl`, content: buildTsl({ name: project.name, tocFileName }) },
    { relPath: `${POI_BASENAME}.toc`, content: buildToc(resolved) },
    { relPath: "README.txt", content: buildReadme(project, resolved) },
  ];

  return { folderName, files, warnings };
}
