// xrefRegistrar.ts — main-process registration of a user's LOOSE `.tmb` into a resolvable bundle
// (design B2). A `.tmb` a user drops in scenery/xref/ does NOT render from a POI: the sim needs a `.tmi`
// scene-index for it, AND — proven by in-sim probe N1 — that `.tmi` must live in the object's OWN
// subfolder (a `.tmi` at the xref root does not resolve). So "registering" a loose `pylon.tmb` means:
//
//   scenery/xref/pylon.tmb      →   scenery/xref/pylon/pylon.tmb
//                                   scenery/xref/pylon/pylon.tmi   (generated by buildTmi — PCT's bytes)
//                                   scenery/xref/pylon/pylon.ttx   (the user's textures, copied)
//
// PCT ships zero model bytes: it only reads the user's own `.tmb` (internal name + bbox) and re-lays
// their files. Electron-free (fs only; dirs injected) so it unit-tests directly, and it mirrors
// installer.ts as the write half of the trust boundary — the bundle name is re-validated with
// isSafeBundleName HERE, every path resolves strictly inside scenery/xref, and each bundle is built in a
// sibling staging folder then swapped in with ONE rename so a crash never leaves a half-registered
// bundle. The original loose `.tmb` is deleted only AFTER its bundle is in place (copy-then-delete): a
// crash mid-way never loses the user's file. A journal in userData records what PCT wrote, so a future
// "unregister" is possible (design Q6: journal now, UI later).

import {
  closeSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { buildTmi } from "../core/export/tmiWriter";
import { isTextTmb, parseUserTmb, type UserTmbGeometry } from "../core/catalog/userTmb";
import { writeFileAtomic } from "./fsAtomic";

/** Scratch folder built beside the destination and swapped in with one rename (mirrors installer.ts).
 *  Not a safe bundle name, so a leftover from a crash is inert. */
const STAGING_SUFFIX = ".pct-staging";
const JOURNAL_FILE = "xref-registry.json";

/** `<afs4UserDir>/scenery/xref` — the only directory registration ever writes into (sibling of poiRoot). */
export function xrefRoot(afs4UserDir: string): string {
  return path.join(afs4UserDir, "scenery", "xref");
}

/** A bundle base is a safe slug: starts alphanumeric, then letters/digits/_/./-. Rejects "..", leading
 *  dots, spaces and path separators — anything that could escape the xref root. XREF_NAME_RE alone is
 *  not enough (it accepts ".."); this is the write-boundary guard, same rationale as isSafePoiFolderName. */
export function isSafeBundleName(base: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(base);
}

/** Resolve `<root>/<base>` only if `base` is a safe slug AND stays inside `root`. */
function resolveBundlePath(root: string, base: string): string {
  if (!isSafeBundleName(base)) throw new Error(`Unsafe bundle name: ${JSON.stringify(base)}`);
  const rootAbs = path.resolve(root);
  const dest = path.resolve(rootAbs, base);
  if (dest !== path.join(rootAbs, base) || !dest.startsWith(rootAbs + path.sep)) {
    throw new Error(`Unsafe bundle name: ${JSON.stringify(base)}`);
  }
  return dest;
}

/** Read the first `n` bytes of a file as UTF-8 — enough to classify a `.tmb` head without decoding a
 *  multi-MB binary. (Mirrors the helper in scan.ts; kept local to keep this module self-contained.) */
function readHead(file: string, n = 512): string {
  const fd = openSync(file, "r");
  try {
    const buf = Buffer.alloc(n);
    const bytes = readSync(fd, buf, 0, n, 0);
    return buf.subarray(0, bytes).toString("utf8");
  } finally {
    closeSync(fd);
  }
}

const sha256 = (s: string): string => createHash("sha256").update(s).digest("hex");
const sha256File = (p: string): string => createHash("sha256").update(readFileSync(p)).digest("hex");

/** One loose `.tmb` that CAN be registered, with everything the write step needs. */
export interface RegisterableBundle {
  base: string; // `.tmb` basename → subfolder + `.tmi` name
  tmbPath: string; // absolute source path of the loose `.tmb`
  geometries: UserTmbGeometry[]; // fed straight to buildTmi
  ttx: string[]; // sibling `.ttx` filenames present at the xref root, copied into the bundle (copy-all, Q2)
  missingTextures: string[]; // `<name>.ttx` the `.tmb` references but that isn't a sibling → renders untextured
}

/** A loose `.tmb` that was NOT registered, with a human reason (shown in the register dialog). */
export interface SkippedTmb {
  path: string;
  reason: string;
}

export interface RegistrationPlan {
  xrefDir: string | null; // resolved scenery/xref, or null if the user has none
  registerable: RegisterableBundle[];
  skipped: SkippedTmb[];
}

/** Dry-run (READ-ONLY): classify every loose root-level `.tmb` in the user's scenery/xref. Non-recursive
 *  by design — a `.tmb` already inside a subfolder is a bundle, not loose. Never throws. */
export function planXrefRegistration(afs4UserDir: string): RegistrationPlan {
  const root = xrefRoot(afs4UserDir);
  let entries;
  try {
    entries = readdirSync(root, { withFileTypes: true });
  } catch {
    return { xrefDir: null, registerable: [], skipped: [] };
  }

  // All `.ttx` at the root — copied wholesale into each bundle (copy-all is safe: over-copy is inert,
  // under-copy renders untextured; Q2). texture_list is used only to WARN about missing ones, not filter.
  const siblingTtx = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".ttx"))
    .map((e) => e.name);

  const registerable: RegisterableBundle[] = [];
  const skipped: SkippedTmb[] = [];

  for (const e of entries) {
    if (!e.isFile() || !e.name.toLowerCase().endsWith(".tmb")) continue;
    const tmbPath = path.join(root, e.name);
    const base = path.basename(e.name, path.extname(e.name));

    if (!isSafeBundleName(base)) {
      skipped.push({ path: tmbPath, reason: "unsafe bundle name" });
      continue;
    }
    if (!isTextTmb(readHead(tmbPath))) {
      skipped.push({ path: tmbPath, reason: "opaque (compiled) .tmb — name/bbox not readable; register it manually" });
      continue;
    }
    const { geometries, textures } = parseUserTmb(readFileSync(tmbPath, "utf8"));
    if (geometries.length === 0) {
      skipped.push({ path: tmbPath, reason: "no derivable geometry (empty or invalid .tmb)" });
      continue;
    }
    const dest = path.join(root, base);
    if (existsSync(dest)) {
      skipped.push({ path: tmbPath, reason: `a "${base}" folder already exists at the xref root` });
      continue;
    }

    const referenced = textures.map((n) => `${n}.ttx`);
    const missingTextures = referenced.filter(
      (t) => !siblingTtx.some((s) => s.toLowerCase() === t.toLowerCase()),
    );
    registerable.push({ base, tmbPath, geometries, ttx: siblingTtx, missingTextures });
  }

  return { xrefDir: root, registerable, skipped };
}

export interface RegisteredBundle {
  base: string;
  path: string; // absolute bundle folder (main-produced → safe to reveal)
  geometries: number;
  ttx: number;
}

export interface RegistrationResult {
  registered: RegisteredBundle[];
  skipped: SkippedTmb[];
  warnings: string[]; // missing-texture notes + any per-bundle failure, for the result surface
}

interface JournalEntry {
  base: string;
  sourceTmbPath: string;
  tmbSha256: string;
  tmiSha256: string;
  files: string[]; // relative filenames written into the bundle (provenance for a future unregister)
  registeredAt: string;
}
type Journal = Record<string, JournalEntry>;

function readJournal(userDataDir: string): Journal {
  try {
    const raw = JSON.parse(readFileSync(path.join(userDataDir, JOURNAL_FILE), "utf8"));
    return raw && typeof raw === "object" ? (raw as Journal) : {};
  } catch {
    return {}; // absent or corrupt → start fresh (the journal is provenance, never the source of truth)
  }
}

function writeJournal(userDataDir: string, journal: Journal): void {
  writeFileAtomic(path.join(userDataDir, JOURNAL_FILE), JSON.stringify(journal, null, 2));
}

/** Sweep scratch folders left by an interrupted earlier registration. */
function sweepStaging(root: string): void {
  let entries;
  try {
    entries = readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (e.isDirectory() && e.name.endsWith(STAGING_SUFFIX)) {
      rmSync(path.join(root, e.name), { recursive: true, force: true });
    }
  }
}

/** Register every loose `.tmb` the plan finds. Re-plans internally (main owns paths; a plan is never
 *  accepted FROM the renderer, P0-2). `now` is injectable for deterministic tests. Each bundle is staged
 *  then swapped in with one rename; the original loose `.tmb` is deleted only after its bundle lands. A
 *  single bundle's failure is isolated (its staging is cleaned, a warning recorded) and the rest proceed. */
export function registerXref(
  afs4UserDir: string,
  userDataDir: string,
  now: string = new Date().toISOString(),
): RegistrationResult {
  const root = xrefRoot(afs4UserDir);
  sweepStaging(root);
  const plan = planXrefRegistration(afs4UserDir);
  const journal = readJournal(userDataDir);
  const registered: RegisteredBundle[] = [];
  const warnings: string[] = [];

  for (const b of plan.registerable) {
    const dest = resolveBundlePath(root, b.base); // re-validate at the write boundary
    const staging = dest + STAGING_SUFFIX;
    rmSync(staging, { recursive: true, force: true });
    try {
      mkdirSync(staging, { recursive: true });
      const tmiText = buildTmi(b.base, b.geometries);
      copyFileSync(b.tmbPath, path.join(staging, `${b.base}.tmb`)); // COPY — don't move yet
      const files = [`${b.base}.tmb`, `${b.base}.tmi`];
      for (const ttx of b.ttx) {
        copyFileSync(path.join(root, ttx), path.join(staging, ttx)); // copy (leave the original — shared)
        files.push(ttx);
      }
      writeFileSync(path.join(staging, `${b.base}.tmi`), tmiText, "utf8");
      renameSync(staging, dest); // atomic swap-in of the complete bundle
      rmSync(b.tmbPath, { force: true }); // NOW delete the original loose `.tmb` — bundle is safely in place

      journal[b.base] = {
        base: b.base,
        sourceTmbPath: b.tmbPath,
        tmbSha256: sha256File(path.join(dest, `${b.base}.tmb`)),
        tmiSha256: sha256(tmiText),
        files,
        registeredAt: now,
      };
      registered.push({ base: b.base, path: dest, geometries: b.geometries.length, ttx: b.ttx.length });
      for (const m of b.missingTextures) {
        warnings.push(`${b.base}: referenced texture ${m} not found — the object may render untextured`);
      }
    } catch (e) {
      rmSync(staging, { recursive: true, force: true }); // leave no half-built bundle behind
      warnings.push(`${b.base}: registration failed (${(e as Error).message})`);
    }
  }

  for (const s of plan.skipped) warnings.push(`Skipped ${path.basename(s.path)}: ${s.reason}`);
  writeJournal(userDataDir, journal);
  return { registered, skipped: plan.skipped, warnings };
}
