// xrefRegistrar.ts — main-process registration of a user's LOOSE `.tmb` into a resolvable bundle
// (design B2). A `.tmb` a user drops in scenery/xref/ does NOT render from a POI: the sim needs a `.tmi`
// scene-index for it, AND — proven by in-sim probe N1 — that `.tmi` must live in the object's OWN
// subfolder (a `.tmi` at the xref root does not resolve). So "registering" a loose `pylon.tmb` means:
//
//   scenery/xref/pylon.tmb      →   scenery/xref/pylon/pylon.tmb
//                                   scenery/xref/pylon/pylon.tmi   (generated by buildTmi — PCT's bytes)
//                                   scenery/xref/pylon/pylon.ttx   (the user's textures, copied)
//
// PCT ships zero model bytes: it only reads the user's own `.tmb` (internal name + bbox) and re-lays
// their files. Electron-free (fs only; dirs injected) so it unit-tests directly, and it mirrors
// installer.ts as the write half of the trust boundary — the bundle name is re-validated with
// isSafeBundleName HERE, every path resolves strictly inside scenery/xref, and each bundle is built in a
// sibling staging folder then swapped in with ONE rename so a crash never leaves a half-registered
// bundle. The original loose `.tmb` is deleted only AFTER its bundle is in place (copy-then-delete): a
// crash mid-way never loses the user's file. A journal in userData records what PCT wrote, so a future
// "unregister" is possible (design Q6: journal now, UI later).

import {
  closeSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { buildTmi } from "../core/export/tmiWriter";
import { isTextTmb, parseUserTmb, type UserTmbGeometry } from "../core/catalog/userTmb";
import { writeFileAtomic } from "./fsAtomic";

/** Scratch folder built beside the destination and swapped in with one rename (mirrors installer.ts).
 *  Not a safe bundle name, so a leftover from a crash is inert. */
const STAGING_SUFFIX = ".pct-staging";
const JOURNAL_FILE = "xref-registry.json";

/** `<afs4UserDir>/scenery/xref` — the only directory registration ever writes into (sibling of poiRoot). */
export function xrefRoot(afs4UserDir: string): string {
  return path.join(afs4UserDir, "scenery", "xref");
}

/** A bundle base is a safe slug: starts alphanumeric, then letters/digits/_/./-. Rejects "..", leading
 *  dots, spaces and path separators — anything that could escape the xref root. XREF_NAME_RE alone is
 *  not enough (it accepts ".."); this is the write-boundary guard, same rationale as isSafePoiFolderName. */
export function isSafeBundleName(base: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(base);
}

/** Resolve `<root>/<base>` only if `base` is a safe slug AND stays inside `root`. */
function resolveBundlePath(root: string, base: string): string {
  if (!isSafeBundleName(base)) throw new Error(`Unsafe bundle name: ${JSON.stringify(base)}`);
  const rootAbs = path.resolve(root);
  const dest = path.resolve(rootAbs, base);
  if (dest !== path.join(rootAbs, base) || !dest.startsWith(rootAbs + path.sep)) {
    throw new Error(`Unsafe bundle name: ${JSON.stringify(base)}`);
  }
  return dest;
}

/** Read the first `n` bytes of a file as UTF-8 — enough to classify a `.tmb` head without decoding a
 *  multi-MB binary. (Mirrors the helper in scan.ts; kept local to keep this module self-contained.) */
function readHead(file: string, n = 512): string {
  const fd = openSync(file, "r");
  try {
    const buf = Buffer.alloc(n);
    const bytes = readSync(fd, buf, 0, n, 0);
    return buf.subarray(0, bytes).toString("utf8");
  } finally {
    closeSync(fd);
  }
}

const sha256 = (s: string): string => createHash("sha256").update(s).digest("hex");
const sha256File = (p: string): string => createHash("sha256").update(readFileSync(p)).digest("hex");

/** A bundle PCT can register, with everything the write step needs. Two shapes, one type:
 *
 *  • `inPlace` — a FOLDER the user already has (`xref/foo/` holding `.tmb` + textures but no `.tmi`).
 *    This is what a real add-on looks like once extracted, and registering it means writing ONE file:
 *    `foo/foo.tmi`. Nothing moves, nothing is deleted.
 *  • loose — a bare `.tmb` at the xref ROOT. PCT builds `xref/<base>/` around it (the v0.3.0 flow). */
export interface RegisterableBundle {
  base: string; // bundle name → the folder AND its `.tmi` basename (the sim keys off `filename`)
  dir: string; // absolute bundle folder: already on disk when inPlace, created by us when loose
  inPlace: boolean;
  tmbPaths: string[]; // the `.tmb` this bundle indexes (exactly one when loose)
  geometries: UserTmbGeometry[]; // union across tmbPaths, fed straight to buildTmi
  ttx: string[]; // `.ttx` filenames at the xref root to copy IN (loose only — an inPlace bundle's are already beside their `.tmb`)
  missingTextures: string[]; // `<name>.ttx` a `.tmb` references but that isn't beside it → renders untextured
}

/** A `.tmb` (or folder) that was NOT registered, with a human reason (shown in the register dialog). */
export interface SkippedTmb {
  path: string;
  reason: string;
}

export interface RegistrationPlan {
  xrefDir: string | null; // resolved scenery/xref, or null if the user has none
  registerable: RegisterableBundle[];
  skipped: SkippedTmb[];
}

/** Classify one bare `.tmb` at the xref ROOT — PCT will build a folder around it. */
function planLooseTmb(
  root: string,
  name: string,
  siblingTtx: string[],
  registerable: RegisterableBundle[],
  skipped: SkippedTmb[],
): void {
  const tmbPath = path.join(root, name);
  const base = path.basename(name, path.extname(name));
  if (!isSafeBundleName(base)) return void skipped.push({ path: tmbPath, reason: "unsafe bundle name" });
  if (!isTextTmb(readHead(tmbPath))) {
    return void skipped.push({
      path: tmbPath,
      reason: "opaque (compiled) .tmb — name/bbox not readable; register it manually",
    });
  }
  const { geometries, textures } = parseUserTmb(readFileSync(tmbPath, "utf8"));
  if (geometries.length === 0) {
    return void skipped.push({ path: tmbPath, reason: "no derivable geometry (empty or invalid .tmb)" });
  }
  const dest = path.join(root, base);
  if (existsSync(dest)) {
    return void skipped.push({ path: tmbPath, reason: `a "${base}" folder already exists at the xref root` });
  }
  const referenced = textures.map((n) => `${n}.ttx`);
  registerable.push({
    base,
    dir: dest,
    inPlace: false,
    tmbPaths: [tmbPath],
    geometries,
    ttx: siblingTtx,
    missingTextures: referenced.filter((t) => !siblingTtx.some((s) => s.toLowerCase() === t.toLowerCase())),
  });
}

/** Classify a FOLDER that holds `.tmb` but no `.tmi` — the shape a real add-on ZIP extracts to. Every
 *  readable `.tmb` in it joins ONE bundle named after the folder; an unreadable one is skipped with its
 *  own reason but does not sink its readable siblings (a partial index still makes those objects work). */
function planFolderBundle(
  dir: string,
  tmbNames: string[],
  ttxNames: string[],
  registerable: RegisterableBundle[],
  skipped: SkippedTmb[],
): void {
  const base = path.basename(dir);
  if (!isSafeBundleName(base)) return void skipped.push({ path: dir, reason: "unsafe folder name" });

  const geometries: UserTmbGeometry[] = [];
  const tmbPaths: string[] = [];
  const referenced = new Set<string>();
  for (const name of tmbNames) {
    const tmbPath = path.join(dir, name);
    if (!isTextTmb(readHead(tmbPath))) {
      skipped.push({ path: tmbPath, reason: "opaque (compiled) .tmb — name/bbox not readable; register it manually" });
      continue;
    }
    const { geometries: g, textures } = parseUserTmb(readFileSync(tmbPath, "utf8"));
    if (g.length === 0) {
      skipped.push({ path: tmbPath, reason: "no derivable geometry (empty or invalid .tmb)" });
      continue;
    }
    geometries.push(...g);
    for (const t of textures) referenced.add(`${t}.ttx`);
    tmbPaths.push(tmbPath);
  }
  if (geometries.length === 0) return; // nothing readable here — each `.tmb` already carries its own reason

  registerable.push({
    base,
    dir,
    inPlace: true,
    tmbPaths,
    geometries,
    ttx: [], // the user's textures already sit beside their `.tmb` — copying would only duplicate them
    missingTextures: [...referenced].filter((t) => !ttxNames.some((s) => s.toLowerCase() === t.toLowerCase())),
  });
}

/** Dry-run (READ-ONLY): find everything in the user's scenery/xref that a `.tmi` doesn't index yet.
 *  RECURSIVE, mirroring findTmi / scan.listUserTmb — see the note there: v0.3.0 looked at the root alone
 *  and therefore never saw a normally-installed add-on, which ships as a ZIP of a folder (#122). A folder
 *  holding a `.tmi` is already resolvable and is left completely alone. Never throws. */
export function planXrefRegistration(afs4UserDir: string): RegistrationPlan {
  const root = xrefRoot(afs4UserDir);
  if (!existsSync(root)) return { xrefDir: null, registerable: [], skipped: [] };

  const registerable: RegisterableBundle[] = [];
  const skipped: SkippedTmb[] = [];

  const walk = (dir: string, isRoot: boolean): void => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    const files = entries.filter((e) => e.isFile());
    const named = (ext: string) => files.filter((e) => e.name.toLowerCase().endsWith(ext)).map((e) => e.name);
    const tmb = named(".tmb");
    // `.ttx` beside the `.tmb`: copied wholesale into a loose bundle (copy-all is safe — over-copy is
    // inert, under-copy renders untextured; Q2). texture_list only WARNS about missing ones, never filters.
    const ttx = named(".ttx");

    if (named(".tmi").length === 0 && tmb.length > 0) {
      if (isRoot) for (const name of tmb) planLooseTmb(root, name, ttx, registerable, skipped);
      else planFolderBundle(dir, tmb, ttx, registerable, skipped);
    }
    for (const e of entries) if (e.isDirectory()) walk(path.join(dir, e.name), false);
  };
  walk(root, true);

  return { xrefDir: root, registerable, skipped };
}

export interface RegisteredBundle {
  base: string;
  path: string; // absolute bundle folder (main-produced → safe to reveal)
  geometries: number;
  ttx: number;
}

export interface RegistrationResult {
  registered: RegisteredBundle[];
  skipped: SkippedTmb[];
  warnings: string[]; // missing-texture notes + any per-bundle failure, for the result surface
}

/** Provenance for a future "unregister". `files` lists ONLY what PCT itself wrote into the bundle — for
 *  an inPlace folder that is the `.tmi` and nothing else, so an unregister can never reach for the user's
 *  own `.tmb`/`.ttx` that were already sitting there. */
interface JournalEntry {
  base: string;
  dir: string;
  inPlace: boolean;
  sourceTmbPath?: string; // loose only: where the original `.tmb` was moved from
  tmbSha256?: string; // loose only
  tmiSha256: string;
  files: string[]; // relative filenames PCT WROTE into the bundle
  registeredAt: string;
}
type Journal = Record<string, JournalEntry>;

/** Assert a discovered bundle dir resolves strictly inside the xref root. Our own walk produced it (and
 *  never follows symlinks — a symlinked dir fails isDirectory()), so this is belt-and-braces at the write
 *  boundary, the same rationale as resolveBundlePath for the loose shape. */
function assertInsideRoot(root: string, dir: string): void {
  const rootAbs = path.resolve(root);
  const dirAbs = path.resolve(dir);
  if (!dirAbs.startsWith(rootAbs + path.sep)) {
    throw new Error(`Bundle escapes the xref root: ${JSON.stringify(dir)}`);
  }
}

function readJournal(userDataDir: string): Journal {
  try {
    const raw = JSON.parse(readFileSync(path.join(userDataDir, JOURNAL_FILE), "utf8"));
    return raw && typeof raw === "object" ? (raw as Journal) : {};
  } catch {
    return {}; // absent or corrupt → start fresh (the journal is provenance, never the source of truth)
  }
}

function writeJournal(userDataDir: string, journal: Journal): void {
  writeFileAtomic(path.join(userDataDir, JOURNAL_FILE), JSON.stringify(journal, null, 2));
}

/** Sweep scratch folders left by an interrupted earlier registration. */
function sweepStaging(root: string): void {
  let entries;
  try {
    entries = readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (e.isDirectory() && e.name.endsWith(STAGING_SUFFIX)) {
      rmSync(path.join(root, e.name), { recursive: true, force: true });
    }
  }
}

/** Register every loose `.tmb` the plan finds. Re-plans internally (main owns paths; a plan is never
 *  accepted FROM the renderer, P0-2). `now` is injectable for deterministic tests. Each bundle is staged
 *  then swapped in with one rename; the original loose `.tmb` is deleted only after its bundle lands. A
 *  single bundle's failure is isolated (its staging is cleaned, a warning recorded) and the rest proceed. */
export function registerXref(
  afs4UserDir: string,
  userDataDir: string,
  now: string = new Date().toISOString(),
): RegistrationResult {
  const root = xrefRoot(afs4UserDir);
  sweepStaging(root);
  const plan = planXrefRegistration(afs4UserDir);
  const journal = readJournal(userDataDir);
  const registered: RegisteredBundle[] = [];
  const warnings: string[] = [];

  for (const b of plan.registerable) {
    try {
      const tmiText = buildTmi(b.base, b.geometries);
      if (b.inPlace) {
        // The folder already IS the bundle — the user's `.tmb` and textures are where the sim wants them
        // (this is byte-for-byte the shape of a working community bundle). Registering is ONE atomic file
        // write: no staging, no move, no delete, nothing to roll back and nothing of the user's to lose.
        assertInsideRoot(root, b.dir);
        writeFileAtomic(path.join(b.dir, `${b.base}.tmi`), tmiText);
        journal[b.base] = {
          base: b.base,
          dir: b.dir,
          inPlace: true,
          tmiSha256: sha256(tmiText),
          files: [`${b.base}.tmi`], // the ONLY byte PCT authored here
          registeredAt: now,
        };
        registered.push({ base: b.base, path: b.dir, geometries: b.geometries.length, ttx: 0 });
      } else {
        const dest = resolveBundlePath(root, b.base); // re-validate at the write boundary
        const staging = dest + STAGING_SUFFIX;
        rmSync(staging, { recursive: true, force: true });
        try {
          mkdirSync(staging, { recursive: true });
          const [tmbPath] = b.tmbPaths; // loose = exactly one
          copyFileSync(tmbPath, path.join(staging, `${b.base}.tmb`)); // COPY — don't move yet
          const files = [`${b.base}.tmb`, `${b.base}.tmi`];
          for (const ttx of b.ttx) {
            copyFileSync(path.join(root, ttx), path.join(staging, ttx)); // copy (leave the original — shared)
            files.push(ttx);
          }
          writeFileSync(path.join(staging, `${b.base}.tmi`), tmiText, "utf8");
          renameSync(staging, dest); // atomic swap-in of the complete bundle
          rmSync(tmbPath, { force: true }); // NOW delete the original — the bundle is safely in place

          journal[b.base] = {
            base: b.base,
            dir: dest,
            inPlace: false,
            sourceTmbPath: tmbPath,
            tmbSha256: sha256File(path.join(dest, `${b.base}.tmb`)),
            tmiSha256: sha256(tmiText),
            files,
            registeredAt: now,
          };
          registered.push({ base: b.base, path: dest, geometries: b.geometries.length, ttx: b.ttx.length });
        } catch (e) {
          rmSync(staging, { recursive: true, force: true }); // leave no half-built bundle behind
          throw e;
        }
      }
      for (const m of b.missingTextures) {
        warnings.push(`${b.base}: referenced texture ${m} not found — the object may render untextured`);
      }
    } catch (e) {
      warnings.push(`${b.base}: registration failed (${(e as Error).message})`);
    }
  }

  for (const s of plan.skipped) warnings.push(`Skipped ${path.basename(s.path)}: ${s.reason}`);
  writeJournal(userDataDir, journal);
  return { registered, skipped: plan.skipped, warnings };
}
