// scripts/gen-categories.ts — regenerate src/core/catalog/categories.data.ts from the
// community-compiled format list (names only), which lists exact object
// names under the ACT/FS4 section headings. Each name is mapped to a PCT
// display category (design §2.4). NAMES ONLY — no dimensions, no IPACS asset bytes.
//
// Run: npm run gen:categories
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DOCS_DIR = path.join(REPO_ROOT, "docs");
const OUT = path.join(REPO_ROOT, "src", "core", "catalog", "categories.data.ts");

// Header tail (after "LISTS - XREF (ACT|FS4) - ") → PCT display taxonomy path.
const CATEGORY_MAP: Record<string, string> = {
  AIRCRAFTS: "aircraft",
  "BUILDINGS - FACTORY": "buildings/factory",
  "BUILDINGS - FUELSTATION": "buildings/fuelstation",
  "BUILDINGS - HANGARS": "buildings/hangar",
  "BUILDINGS - OFFICE": "buildings/office",
  "BUILDINGS - RESERVOIR": "buildings/reservoir",
  "BUILDINGS - RESIDENTIAL": "buildings/residential",
  "BUILDINGS - TERMINAL": "buildings/terminal",
  "BUILDINGS - TOWER": "buildings/tower",
  "ITEMS - BARREL": "items/barrel",
  "ITEMS - CARDBOARD BOX": "items/box",
  "ITEMS - CONTAINER": "items/container",
  "ITEMS - LIGHTING": "items/lighting",
  "ITEMS - TECHNICAL": "items/technical",
  "ITEMS - TRASHCAN": "items/trashcan",
  "ITEMS - WATERTANK": "items/watertank",
  "ITEMS - OTHER": "items/other",
  "VEHICLES - AIRPORT VEHICLES": "vehicles/airport",
  "VEHICLES - CARAVAN": "vehicles/caravan",
  "VEHICLES - CARS": "vehicles/cars",
  "VEHICLES - TRUCK": "vehicles/truck",
  "VEHICLES - OTHER": "vehicles/other",
  CHURCHES: "churches",
  "COMMUNICATION TOWERS": "comm-towers",
  CONSTRUCTIONS: "construction",
  FURNITURES: "furniture",
  JETWAYS: "jetways",
  PEOPLE: "people",
  VARIOUS: "various",
};

function findBibleFile(): string {
  const hit = readdirSync(DOCS_DIR).find((f) =>
    /^FS4_ADDON_FILES__TSL_TOC__.*\.txt$/i.test(f),
  );
  if (!hit) throw new Error(`No FS4_ADDON_FILES__TSL_TOC__*.txt found in ${DOCS_DIR}`);
  return path.join(DOCS_DIR, hit);
}

function main(): void {
  const file = findBibleFile();
  const lines = readFileSync(file, "utf8").split(/\r?\n/);

  const byName = new Map<string, string>();
  const perCat = new Map<string, number>();
  let current: string | null = null;
  let dupes = 0;

  const headerRe = /^LISTS - XREF \((?:ACT|FS4)\) - (.+)$/;
  const nameRe = /^ {4,}([A-Za-z0-9_]+)\s*$/;

  for (const line of lines) {
    if (/^\S/.test(line)) {
      // Column-0 structural line. Markers (____), dividers (==== ---- .... ####), raw markup
      // (<...) and "// NOTE" comment lines are within-section decoration — the names that
      // follow still belong to the current category, so DON'T reset it here.
      if (/^[/_=.#<-]/.test(line)) continue;
      const m = headerRe.exec(line);
      if (m) {
        const tail = m[1].split(/\s{2,}/)[0].trim(); // drop trailing "(ACT AND NOT ACT)" notes
        current = CATEGORY_MAP[tail] ?? null;
      } else {
        current = null; // any other header ends the current name list
      }
      continue;
    }
    if (!current) continue;
    const nm = nameRe.exec(line);
    if (!nm) continue;
    const name = nm[1];
    const prev = byName.get(name);
    if (prev === undefined) {
      byName.set(name, current);
      perCat.set(current, (perCat.get(current) ?? 0) + 1);
    } else if (prev !== current) {
      dupes++;
      console.warn(`  ! "${name}" listed under both ${prev} and ${current} — keeping first`);
    }
  }

  const names = [...byName.keys()].sort((a, b) => {
    const ca = byName.get(a) as string;
    const cb = byName.get(b) as string;
    return ca === cb ? a.localeCompare(b) : ca.localeCompare(cb);
  });

  const body = names
    .map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(byName.get(n))},`)
    .join("\n");

  const out = `// GENERATED by scripts/gen-categories.ts — DO NOT EDIT BY HAND.
// Source: the community-compiled format list (names only).
// Exact object name → PCT display category. Names only; no dimensions, no IPACS bytes.
// ${names.length} names across ${perCat.size} categories. Regenerate: npm run gen:categories

export const CATEGORY_BY_NAME: Record<string, string> = {
${body}
};
`;

  writeFileSync(OUT, out);

  console.log(`Wrote ${path.relative(REPO_ROOT, OUT)}`);
  console.log(`  ${names.length} names, ${perCat.size} categories`);
  for (const [cat, count] of [...perCat.entries()].sort((a, b) => b[1] - a[1])) {
    console.log(`    ${cat.padEnd(22)} ${count}`);
  }
  if (dupes) console.log(`  (${dupes} duplicate name(s) ignored)`);
}

main();
